from pathlib import Path
import json, hashlib
P=Path(__file__).resolve().parent
# (stroke, upper x, upper width, upper thickness, bottom right, x shift)
variants={'previous':(10,28,28,10,46,0),'thin-l':(8.5,28,28,10,46,0),'inward':(10,24,28,10,44,2),'balanced':(9,25,26,9,44,2.5),'settled':(9,24,23,7,44,4.5)}
BRAND_RED='#c95e55'
def svg(key='settled',ink='currentColor',bars=None,label='les Privilege',ident='brand',accent=None,accent_row='top'):
 t,x,w,h,end,shift=variants[key]; l=8;right=l+t;top=8;bottom=56;y=bottom-t;r=t/4
 d=f'M{l+r} {top}H{right-r}Q{right} {top} {right} {top+r}V{y-r}Q{right} {y} {right+r} {y}H{end-r}Q{end} {y} {end} {y+r}V{bottom-r}Q{end} {bottom} {end-r} {bottom}H{l+r}Q{l} {bottom} {l} {bottom-r}V{top+r}Q{l} {top} {l+r} {top}Z'
 upper_y, middle_y = (12,30) if key=="settled" else (8,(8+y)/2)
 return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-labelledby="{ident}-title"><title id="{ident}-title">{label}</title><g transform="translate({shift} 0)"><path fill="{ink}" d="{d}"/><g fill="{bars or ink}"><rect fill="{accent if accent and accent_row=='top' else bars or ink}" x="{x}" y="{upper_y}" width="{w}" height="{h}" rx="{h/4}"/><rect fill="{accent if accent and accent_row=='middle' else bars or ink}" x="{x}" y="{middle_y}" width="{w}" height="{h}" rx="{h/4}"/></g></g></svg>\n'''
exports={'mark.svg':svg(),'mark-light.svg':svg(ink='#242d33'),'mark-dark.svg':svg(ink='#e4ebef'),'mark-tonal-light.svg':svg(ink='#242d33',bars='#6f7e88'),'mark-tonal-dark.svg':svg(ink='#e4ebef',bars='#95a5af')}
exports.update({'mark-tritone-light.svg':svg(ink='#242d33',bars='#6f7e88',accent=BRAND_RED),'mark-tritone-dark.svg':svg(ink='#e4ebef',bars='#95a5af',accent=BRAND_RED),'mark-tritone-middle-light.svg':svg(ink='#242d33',bars='#6f7e88',accent=BRAND_RED,accent_row='middle'),'mark-tritone-middle-dark.svg':svg(ink='#e4ebef',bars='#95a5af',accent=BRAND_RED,accent_row='middle')})
for name,value in exports.items():(P/name).write_text(value)
css='''*{box-sizing:border-box}body{margin:0;background:#edf1f3;color:#242d33;font:15px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:44px 40px}header{border-bottom:1px solid #bdc8cf;padding-bottom:24px}h1{font-size:46px;line-height:1.15;letter-spacing:-.035em;margin:10px 0 14px;font-weight:600}h2{font-size:16px;margin:0}p{color:#54616a;margin:10px 0}.eyebrow{font:12px ui-monospace,monospace;letter-spacing:.12em}section{margin-top:30px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.sample{min-width:0;border-top:1px solid #bdc8cf;padding-top:14px}.glyph{height:148px;display:grid;place-items:center}.glyph svg{width:128px;height:128px}svg{display:block;width:100%;height:100%}.selected{border-top:2px solid #242d33}.sample p{font-size:13px}.signature{display:flex;align-items:center;gap:14px}.signature svg{width:40px;height:40px;flex:none}.signature strong{font-size:27px;letter-spacing:-.03em;font-weight:550;white-space:nowrap}.panels{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px}.panel{min-width:0;padding:24px;background:#f9fbfc;border:1px solid #bdc8cf}.dark{background:#202b32;color:#e4ebef;border-color:#465762}.dark p{color:#b2c1ca}.panel h3{font:30px/1.2 Georgia,serif;font-weight:400;margin:22px 0 12px}.ladder{display:flex;gap:28px;align-items:end;flex-wrap:wrap}.size{display:flex;align-items:center;flex-direction:column;gap:6px}.size small{font:11px ui-monospace,monospace}.size span{display:block}.comparison{display:grid;grid-template-columns:180px minmax(0,1fr);align-items:center;gap:28px;border-top:1px solid #bdc8cf;padding-top:20px}.comparison img{width:180px;height:180px}.comparison p{max-width:70ch}.stamp{overflow-wrap:anywhere;font:11px ui-monospace,monospace;letter-spacing:.08em;color:#a8403b}.links{display:flex;gap:20px;flex-wrap:wrap}a{color:inherit;text-underline-offset:4px}footer{font-size:12px;color:#54616a;margin-top:24px;border-top:1px solid #bdc8cf;padding-top:14px}@media(max-width:600px){main{padding:28px 20px}h1{font-size:38px}.grid{grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.glyph{height:125px}.glyph svg{width:100px;height:100px}.panels{grid-template-columns:1fr}.signature strong{font-size:24px}.comparison{grid-template-columns:100px minmax(0,1fr);gap:14px}.comparison img{width:100px;height:100px}.comparison p{font-size:13px}}'''
html=f'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>les Privilege · Optical study</title><style>{css}</style><main><header><div class="eyebrow">MAKER’S MARK / OPTICAL REVISION 03</div><h1>les Privilege</h1><p>对外署名。le 是图形标记；先认出厂牌，再读出字母。</p></header><section class="grid">'
for key,title,desc in [('previous','00 / 前版','10 px 等粗 · 双横离竖笔 10'),('balanced','01 / Paper v1','全体 9 · 双横长 26 · 留白 8'),('settled','02 / 收尾 · 黑色宗','L 9 · 双横 7 × 23 · 顶端下退 4')]:
 html+=f'<div class="sample {"selected" if key=="settled" else ""}"><h2>{title}</h2><div class="glyph">{svg(key,ident=key)}</div><p>{desc}</p></div>'
html+='</section><section class="panels"><div class="panel"><h2>03 / 上横红 · 推荐</h2><div class="glyph">'+svg(ink='#242d33',bars='#6f7e88',accent=BRAND_RED,ident='red-top')+'</div><p>红 → 浅灰 → 深色 L。上端有信号，底部有支撑。</p></div><div class="panel"><h2>04 / 中横红 · 对照</h2><div class="glyph">'+svg(ink='#242d33',bars='#6f7e88',accent=BRAND_RED,accent_row='middle',ident='red-middle')+'</div><p>浅灰 → 红 → 深色 L。红色集中在结构内部。</p></div></section><section class="panels"><div class="panel"><div class="signature">'+svg(ink='#242d33',bars='#6f7e88',accent=BRAND_RED,ident='signature')+'<strong>les Privilege</strong></div><h3>Schema Engineering</h3><p>彩色宗 / Dystopia · 上横红</p></div><div class="panel dark"><div class="signature">'+svg(ink='#e4ebef',ident='dark')+'<strong>les Privilege</strong></div><h3>CourtWork</h3><p>黑色宗 / 对标 Anthropic A\\ · 深底反白</p></div></section><section><h2>16–64 px / 黑色宗与彩色宗</h2>'
for mode in ['mono','tonal','mono-dark','tonal-dark']:
 html+=f'<div class="ladder {"dark" if mode.endswith("dark") else ""}" style="margin-top:16px;padding:12px">'
 for n in [16,20,24,32,48,64]:html+=f'<div class="size"><span style="width:{n}px;height:{n}px">{svg(ink="#e4ebef" if mode.endswith("dark") else "#242d33",bars=("#95a5af" if mode.endswith("dark") else "#6f7e88") if mode.startswith("tonal") else None,accent=BRAND_RED if mode.startswith("tonal") else None,ident=mode+str(n))}</span><small>{n}</small></div>'
 html+='</div>'
html+='</section><section class="comparison"><img src="../../engineering/research/le-brand-2026-09-11/reference-2.jpeg" alt="用户提供的 Anthropic 黑色字母图标参考"><div><h2>Anthropic / 对照登记</h2><p>参考其紧凑的字母拼合与厂商标记尺度。les Privilege 使用连续 L、悬浮双横与柔和圆角，来自 CourtWork 的几何母题；保留自己的冷灰体系。</p><p>less privilege 的双关与《红与黑》作为品牌暗层。三色标记让红色进入一条横笔，L 用深色、另一横用浅灰；作为 Dystopia 与 anti-Anthropic 的 fake lab 品牌表达。</p><div class="stamp">RESEARCH / SOFTWARE — MAKER’S SIGNATURE</div></div></section><section class="links"><a href="mark-tritone-light.svg">Tritone light</a><a href="mark-tritone-dark.svg">Tritone dark</a><a href="mark.svg">Mono SVG</a><a href="mark-light.svg">Light</a><a href="mark-dark.svg">Dark</a><a href="mark-tonal-light.svg">Tonal light</a><a href="mark-tonal-dark.svg">Tonal dark</a></section><footer>名称已登记：les Privilege。几何为 Astra 收尾版本；此页为本地对照，Paper 待定稿资产接入，未部署。Anthropic 图为用户参考原图，不属于导出资产。</footer></main></html>'
(P/'index.html').write_text(html)
(P/'manifest.json').write_text(json.dumps({'name':'les Privilege','handle':'lesPrivilege','mark':'le','status':'astra-optical-finish; pending-independent-review; not-published','revision':'optical-03','paletteRevision':'common-red-v1','grid':64,'geometry':{'LStroke':9,'barThickness':7,'barLength':23,'barX':24,'barY':[12,30],'stemBarGap':7,'topInset':4,'LRadius':2.25,'barRadius':1.75,'inkBounds':[12.5,8,51.5,56],'lowerRight':48.5,'translateX':4.5},'palette':{'light':{'L':'#242d33','secondary':'#6f7e88','red':BRAND_RED},'dark':{'L':'#e4ebef','secondary':'#95a5af','red':BRAND_RED}},'families':{'color':'tritone; Dystopia','black':'monochrome; Anthropic A-backslash reference'},'recommendedColor':'red top bar; gray middle bar; dark L on light ground; common brand red across schemes','brandColorRole':'brand marker only; not text or product status','variants':variants,'files':[{'path':k,'sha256':hashlib.sha256(v.encode()).hexdigest()} for k,v in exports.items()]},indent=2)+'\n')
board='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>les Privilege · Two families</title><style>*{box-sizing:border-box}body{margin:0;color:#242d33;background:#edf1f3;font:16px system-ui}main{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:#bdc8cf}.tile{height:230px;padding:30px;background:#f9fbfc}.dark{background:#202b32;color:#e4ebef}small{font:11px ui-monospace,monospace;letter-spacing:.1em}.lockup{display:flex;align-items:center;gap:18px;margin-top:40px}.lockup svg{width:64px;height:64px;flex:none}.lockup strong{font-size:32px;font-weight:550;letter-spacing:-.04em}@media(max-width:600px){main{grid-template-columns:1fr}.tile{height:210px;padding:24px}.lockup{margin-top:32px}.lockup strong{font-size:28px}}</style><main>'
for key,dark,color in [('COLOR',False,True),('BLACK',False,False),('COLOR',True,True),('BLACK',True,False)]:
 ink='#e4ebef' if dark else '#242d33';bars=('#95a5af' if dark else '#6f7e88') if color else None;red=BRAND_RED if color else None
 board+=f'<div class="tile {"dark" if dark else ""}"><small>{key} / {"DARK GROUND" if dark else "LIGHT GROUND"}</small><div class="lockup">'+svg(ink=ink,bars=bars,accent=red,ident=key+str(dark))+'<strong>les Privilege</strong></div></div>'
(P/'identity.html').write_text(board+'</main></html>')
