from pathlib import Path
import hashlib,json
P=Path(__file__).resolve().parent
stem='M10.5 8H15.5Q18 8 18 10.5V43.5Q18 46 20.5 46H43.5Q46 46 46 48.5V53.5Q46 56 43.5 56H10.5Q8 56 8 53.5V10.5Q8 8 10.5 8Z'
def svg(ink='currentColor',bars=None):
 return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-labelledby="le-title le-desc">
<title id="le-title">LE</title><desc id="le-desc">LE monogram: a continuous L and two equal horizontal strokes. The lower arm is shorter, and the top edges align.</desc>
<path fill="{ink}" d="{stem}"/>
<g fill="{bars or ink}"><rect x="28" y="8" width="28" height="10" rx="2.5"/><rect x="28" y="27" width="28" height="10" rx="2.5"/></g>
</svg>\n'''
variants={'le.svg':svg(),'le-light.svg':svg('#242d33'),'le-dark.svg':svg('#e4ebef'),'le-hierarchy-light.svg':svg('#242d33','#6f7e88'),'le-hierarchy-dark.svg':svg('#e4ebef','#95a5af')}
for name,value in variants.items():(P/name).write_text(value)
# Unique title IDs for inline repeated marks.
def mark(ink='currentColor',bars=None,key='mark'):
 return svg(ink,bars).replace('le-title',key+'-title').replace('le-desc',key+'-desc')
original=(P.parents[1]/'geometry/mark.svg').read_text().replace('<svg ', '<svg fill="currentColor" ',1)
sizes=''.join(f'<div><span style="width:{n}px;height:{n}px">{mark(key="size"+str(n))}</span><small>{n}</small></div>' for n in [16,20,24,32,48,64])
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LE · Brand study</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf1f3;color:#242d33;font:16px/1.6 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:56px 40px}header{border-bottom:1px solid #bdc8cf;padding-bottom:28px}h1{font-size:44px;line-height:1.15;letter-spacing:-.05em;margin:12px 0}p{max-width:68ch;color:#54616a}.eyebrow,small{font:12px/1.5 ui-monospace,monospace;letter-spacing:.08em}section{margin-top:44px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:32px}.sample{border-top:1px solid #bdc8cf;padding-top:20px}.glyph{height:180px;display:flex;align-items:center;justify-content:center}.glyph svg{width:128px;height:128px}h2{font-size:17px;font-weight:600;margin:0}svg{display:block;width:100%;height:100%}.sizes{display:flex;gap:36px;align-items:end;flex-wrap:wrap}.sizes div{display:flex;align-items:center;flex-direction:column;gap:12px}.sizes span{display:block}.applications{display:grid;grid-template-columns:1fr 1fr;gap:24px}.paper{background:#f9fbfc;padding:28px;border:1px solid #bdc8cf}.signature{display:flex;gap:14px;align-items:center}.signature svg{width:40px;height:40px}.signature strong{font-size:26px;letter-spacing:-.04em}.paper h3{font:36px/1.1 Georgia,serif;font-weight:400;margin:28px 0 12px}.dark{background:#202b32;color:#e4ebef;border-color:#465762}.dark p{color:#b2c1ca}.download{display:flex;gap:24px;flex-wrap:wrap;margin-top:24px}a{color:inherit;text-underline-offset:4px}footer{border-top:1px solid #bdc8cf;margin-top:48px;padding-top:16px;color:#54616a;font-size:13px}@media(max-width:600px){main{padding:32px 24px}.grid{grid-template-columns:1fr}.glyph{height:140px}.applications{grid-template-columns:1fr}h1{font-size:36px}.sizes{gap:24px}}@media(forced-colors:active){body,.paper,.dark{background:Canvas;color:CanvasText}.paper svg *[fill]{fill:CanvasText}}
</style><main><header><div class="eyebrow">LE / IDENTITY STUDY 01</div><h1>One joined stroke.<br>A distinct signature.</h1><p>保留 CourtWork 的长、长、短节奏。短横与竖笔连成 L，两条上横保留 E 的暗示。以连续性区分厂商署名与产品图标。</p></header><section class="grid">'''
for title,desc,s in [('00 · CourtWork','原生几何 / 保留产品身份',original),('01 · LE / Primary','单色 / 推荐作为独立署名',mark(key='primary')),('02 · LE / Tonal','浅色双横 / 接近母体的对照',mark('#242d33','#6f7e88','tonal'))]:html+=f'<div class="sample"><h2>{title}</h2><div class="glyph">{s}</div><p>{desc}</p></div>'
html+='</section><section><h2>Small-size rhythm</h2><p>16–64 px · 同一几何，未添加小号专用变体。</p><div class="sizes">'+sizes+'</div></section><section class="applications"><div class="paper"><div class="signature">'+mark(key='signature')+'<strong>Leo</strong></div><h3>Schema Engineering</h3><p>Paper 署名场景 · 候选示意</p></div><div class="paper dark"><div class="signature">'+mark('#e4ebef',key='dark-signature')+'<strong>LE</strong></div><h3>The work remains.</h3><p>独立厂商品牌 · 深色发布面示意</p></div></section><nav class="download"><a href="le.svg">SVG / currentColor</a><a href="le-light.svg">Light</a><a href="le-dark.svg">Dark</a><a href="le-hierarchy-light.svg">Tonal light</a></nav><footer>原生 SVG 几何探索。LE 为拟设厂商品牌；尚未替换 CourtWork 标识或公开 Paper 署名。无字体、图片或脚本依赖的图标导出。</footer></main></html>'
(P/'index.html').write_text(html)
(P/'manifest.json').write_text(json.dumps({'status':'candidate','source':'brand/geometry/mark.svg','source_sha256':hashlib.sha256((P.parents[1]/'geometry/mark.svg').read_bytes()).hexdigest(),'grid':64,'inkBounds':[8,8,56,56],'stroke':10,'rowGap':9,'stemRowGap':10,'radius':2.5,'upperLength':28,'lowerVisibleLength':18,'files':[{'path':k,'sha256':hashlib.sha256(v.encode()).hexdigest()} for k,v in variants.items()]},indent=2)+'\n')
