import {
  BriefcaseBusiness,
  CalendarClock,
  Camera,
  Clipboard,
  ChevronDown,
  ChevronRight,
  Cog,
  Columns2,
  File,
  FileText,
  Ellipsis,
  FolderOpen,
  Image,
  MessageSquareText,
  MessageCircle,
  Mic,
  Minus,
  Package,
  PanelLeft,
  PanelRight,
  PanelsTopLeft,
  Paperclip,
  Plus,
  RotateCcw,
  RotateCw,
  Rows2,
  Scan,
  Send,
  SendHorizontal,
  ThumbsDown,
  ThumbsUp,
  Volume2,
  X,
  type LucideIcon,
} from 'lucide-react';

const standardIcons = {
  'briefcase-business': BriefcaseBusiness,
  'message-square-text': MessageSquareText,
  'panels-top-left': PanelsTopLeft,
  'rows-two': Rows2,
  'columns-two': Columns2,
  'rotate-counter-clockwise': RotateCcw,
  // 过渡别名：并发案件工作流提交后删除。
  case: BriefcaseBusiness,
  conversation: MessageSquareText,
  panels: PanelsTopLeft,
  settings: Cog,
  compare: Rows2,
  stack: Rows2,
  columns: Columns2,
  reset: RotateCcw,
  cog: Cog,
  plus: Plus,
  minus: Minus,
  'scan-frame': Scan,
  paperclip: Paperclip,
  'folder-open': FolderOpen,
  'send-horizontal': SendHorizontal,
  camera: Camera,
  mic: Mic,
  x: X,
  'file-text': FileText,
  file: File,
  image: Image,
  'rotate-clockwise': RotateCw,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  package: Package,
  'calendar-clock': CalendarClock,
  send: Send,
  clipboard: Clipboard,
  'message-circle': MessageCircle,
  ellipsis: Ellipsis,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'volume-two': Volume2,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
} satisfies Record<string, LucideIcon>;

type StandardIconName = keyof typeof standardIcons;
type IconName = StandardIconName;

export function Icon({ name, scope = 'chrome' }: { name: IconName; scope?: 'chrome' | 'turn' }) {
  const Component = standardIcons[name];
  return <Component className={scope === 'turn' ? 'turn-icon' : 'line-icon'} data-icon-scope={scope} aria-hidden="true" />;
}

export type { IconName };
