#!/usr/bin/env node
// Fresh synthetic capture state for the post-merge Pages batch.
//
// This script intentionally seeds through the product's HTTP routes and the
// local deterministic fake provider. It never opens a browser, touches SQLite,
// or changes UI state. Use --active none for stable screenshots, --active
// approval to leave one real permission request waiting, or --active running
// to leave one real slow model stream in progress.
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { startServer } from '../../app/server/index.mjs';
import { FAKE_CREDENTIAL_KEY } from '../../app/runtime/pi-session-runtime.mjs';
import { SYNTHETIC_SOURCES, NORMAL_FACTS } from '../../app/domains/inbound-nda/fixtures.mjs';
import { buildReview } from '../../app/domains/inbound-nda/index.mjs';

const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i === -1 ? fallback : process.argv[i + 1];
};
const active = arg('--active', 'approval');
if (!['none', 'approval', 'running'].includes(active)) throw new Error('--active must be none, approval, or running');
const manifestPath = arg('--manifest', path.join(tmpdir(), `courtwork-capture-fixture-${randomUUID()}.json`));
const retain = process.argv.includes('--retain');
const sourceSha = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();

let reviewDomain = null;
let attentionProjectId = null;
let attentionId = null;
let runningMode = false;

function turnToolCount(body) {
  const messages = Array.isArray(body?.messages) ? body.messages : [];
  let start = 0;
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    if (messages[i]?.role === 'user') { start = i + 1; break; }
  }
  return messages.slice(start).filter(message => message?.role === 'tool').length;
}

// Natural-language prompts are the visible user inputs in the eventual
// browser capture. Tool calls are emitted only after the real runtime asks the
// provider; follow-up requests receive the tool result and a normal final
// answer. IDs are generated by the product, never supplied as fake records.
function fakeResponder({ body, mode }) {
  const count = turnToolCount(body);
  const id = `capture-fixture-response-${randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  if (mode.startsWith('Prepare a source-backed review') && count === 0) {
    return { kind: 'tool', id, created, toolCallId: `capture-submit-${randomUUID()}`, name: 'se_submit_candidate', arguments: { domain: reviewDomain } };
  }
  if (mode.startsWith('Write the final review memo') && count === 0) {
    return {
      kind: 'tool', id, created, toolCallId: `capture-write-${randomUUID()}`, name: 'ws_write',
      arguments: {
        path: 'out/project-cedar-review.md',
        text: '# Project Cedar review memo\n\nSource-backed working draft.\n\n- Purpose: evaluate Project Cedar acquisition.\n- Term: three years after the Effective Date.\n- Status: pending human Review.\n',
      },
    };
  }
  if (mode.startsWith('Write the exhibit index') && count === 0) {
    return {
      kind: 'tool', id, created, toolCallId: `capture-approval-${randomUUID()}`, name: 'ws_write',
      arguments: { path: 'out/exhibit-index.md', text: '# Exhibit index\n\nExhibits prepared for review.\n' },
    };
  }
  if (mode.startsWith('Inspect the current workspace') && count === 0) {
    return { kind: 'tool', id, created, toolCallId: `capture-read-${randomUUID()}`, name: 'ws_read', arguments: { path: 'out/project-cedar-review.md' } };
  }
  if (mode.startsWith('Help me inspect the review item') && count === 0) {
    return { kind: 'tool', id, created, toolCallId: `capture-projects-${randomUUID()}`, name: 'attention_projects', arguments: {} };
  }
  if (mode.startsWith('Help me inspect the review item') && count === 1) {
    return { kind: 'tool', id, created, toolCallId: `capture-list-${randomUUID()}`, name: 'attention_list', arguments: { project_id: attentionProjectId } };
  }
  if (mode.startsWith('Help me inspect the review item') && count === 2) {
    return { kind: 'tool', id, created, toolCallId: `capture-inspect-${randomUUID()}`, name: 'attention_inspect', arguments: { project_id: attentionProjectId, attention_id: attentionId, expected_revision: 1 } };
  }
  if (runningMode && mode.startsWith('Inspect the current workspace') && count > 0) {
    const paragraphs = Array.from({ length: 28 }, (_, index) => `Progress update ${index + 1}: I am checking the source-backed review and workspace artifact. The run is still active while I stream the result for review. The review remains pending your decision.`);
    return { kind: 'text', id, created, slow: true, text: paragraphs.join('\n\n') };
  }
  if (count > 0) return { kind: 'text', id, created, text: 'I inspected the requested materials and recorded the result for review.' };
  return { kind: 'text', id, created, text: `I received: ${mode || '(empty input)'}` };
}

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const TERMINAL = new Set(['completed', 'failed', 'cancelled', 'unknown']);

const dataDir = await mkdtemp(path.join(tmpdir(), 'courtwork-capture-fixture-'));
const runtime = await startServer({ dataDir, port: 0, fakeResponder });
const headers = { 'content-type': 'application/json', 'x-work-token': runtime.token };
async function api(method, route, body) {
  const response = await fetch(runtime.url + '/api/v5' + route, {
    method, headers, body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  const json = text ? JSON.parse(text) : null;
  if (!response.ok) throw new Error(`${method} ${route} -> ${response.status}: ${text}`);
  return json;
}
async function poll(runId, until = status => TERMINAL.has(status), timeoutMs = 15000) {
  const start = Date.now();
  for (;;) {
    const run = (await api('GET', `/runs/${runId}`)).run;
    if (until(run.status)) return run;
    if (Date.now() - start > timeoutMs) throw new Error(`run ${runId} timed out at ${run.status}`);
    await sleep(25);
  }
}
async function waitEvent(sessionId, runId, type, timeoutMs = 15000) {
  const start = Date.now();
  for (;;) {
    const events = (await api('GET', `/sessions/${sessionId}/events?afterSeq=0`)).events;
    const found = events.find(event => event.runId === runId && event.type === type);
    if (found) return found;
    if (Date.now() - start > timeoutMs) throw new Error(`event ${type} missing for ${runId}`);
    await sleep(25);
  }
}
async function makeSession(projectId, title, permissionMode) {
  return (await api('POST', '/sessions', { projectId, title, ...(permissionMode ? { permissionMode } : {}) })).session;
}
async function bind(session, input) {
  await api('POST', `/sessions/${session.id}/extension`, { extensionId: 'inbound-nda', input });
  return (await api('GET', `/sessions/${session.id}/surface`)).projection;
}
async function runNatural(session, input, commandId) {
  const run = (await api('POST', `/sessions/${session.id}/runs`, { commandId, input })).run;
  return { run, settled: await poll(run.id) };
}

const result = {
  schemaVersion: 1,
  fixtureVersion: 1,
  dataClass: 'synthetic; actual HTTP/Pi loopback/Core; no real provider',
  source_sha: sourceSha,
  active,
  origin: runtime.url,
  data_dir: dataDir,
  generated_at: new Date().toISOString(),
  scenarios: {},
};
try {
  await api('PUT', '/provider-credential', { connectionId: 'catalog-fake-openai-loopback', apiKey: FAKE_CREDENTIAL_KEY });
  await api('PUT', '/provider-config', { provider: 'fake-openai-loopback', model: 'fake-model', api: 'openai-completions' });
  await api('POST', '/extensions/inbound-nda/lifecycle', { action: 'load' });

  const project = (await api('POST', '/projects', { name: 'Project Cedar review' })).project;
  const otherProject = (await api('POST', '/projects', { name: 'Northside housing ledger' })).project;
  result.projects = { primary: project.id, other: otherProject.id };
  attentionProjectId = project.id;

  // Matter + pending Review candidate. The candidate is produced by a real
  // Run using a source projection returned by the extension binding.
  const matterSession = await makeSession(project.id, 'Inbound NDA — Project Cedar');
  const matterProjection = await bind(matterSession, { title: 'Inbound NDA — Project Cedar', sourceText: SYNTHETIC_SOURCES[0].text, facts: NORMAL_FACTS });
  reviewDomain = buildReview({ sources: matterProjection.sources, facts: matterProjection.domain.facts });
  const reviewRun = await runNatural(matterSession, 'Prepare a source-backed review for Project Cedar using the approved source.', 'capture-review');
  const reviewSurface = await api('GET', `/sessions/${matterSession.id}/surface`);
  result.sessions = { matter: matterSession.id };
  result.runs = { review: reviewRun.run.id };
  result.matter = { id: matterProjection.matter.id, source: matterProjection.sources[0].id, candidate: reviewSurface.projection.candidates[0]?.id ?? null };
  result.scenarios.matter = { sessionId: matterSession.id, surface: `/sessions/${matterSession.id}/surface` };
  result.scenarios.review = { sessionId: matterSession.id, runId: reviewRun.run.id, candidateId: result.matter.candidate, state: 'pending human Review' };

  // A second Matter becomes the genuine stale Spark derivation after a
  // versioned source replacement through the human action contract.
  const sparkSession = await makeSession(project.id, 'Source refresh — Spark derivation');
  const sparkProjection = await bind(sparkSession, { title: 'Source refresh — Spark derivation', sourceText: SYNTHETIC_SOURCES[0].text, facts: NORMAL_FACTS });
  const sparkSurface = await api('GET', `/sessions/${sparkSession.id}/surface`);
  const original = sparkProjection.sources[0];
  const changedText = `${original.text}\n\n5. Notice. Notices must be delivered in writing to the designated project representatives.\n`;
  const changed = { ...original, version: 2, text: changedText, digest: createHash('sha256').update(changedText).digest('hex') };
  const action = await api('POST', `/sessions/${sparkSession.id}/actions`, {
    extensionId: 'inbound-nda', generation: sparkSurface.extension.generation, action: 'replace_sources',
    payload: { sources: [changed], revision: 2 },
  });
  const derivations = await api('GET', `/work-derivations?projectId=${encodeURIComponent(project.id)}`);
  result.sessions.spark = sparkSession.id;
  result.scenarios.spark = { sessionId: sparkSession.id, actionRevision: action.receipt?.revision ?? action.revision ?? null, derivations, state: 'source version changed through HTTP action' };

  // Artifact is written by ws_write in a normal draft-permission Run.
  const artifactSession = await makeSession(project.id, 'Final review memo — working artifact');
  const artifactRun = await runNatural(artifactSession, 'Write the final review memo to the workspace.', 'capture-artifact');
  const workspace = await api('GET', `/sessions/${artifactSession.id}/workspace`);
  result.sessions.artifact = artifactSession.id;
  result.runs.artifact = artifactRun.run.id;
  result.scenarios.artifact = { sessionId: artifactSession.id, runId: artifactRun.run.id, workspace };

  // Matter continuation uses the supported ownership/origin binding route.
  const continuitySession = await makeSession(project.id, 'Continue Project Cedar review');
  await api('POST', `/sessions/${continuitySession.id}/extension`, { extensionId: 'inbound-nda', input: { existingMatterId: matterProjection.matter.id, fromSessionId: matterSession.id } });
  result.sessions.continuity = continuitySession.id;
  result.scenarios.continuity = { sessionId: continuitySession.id, existingMatterId: matterProjection.matter.id, fromSessionId: matterSession.id };

  // Attention is a typed Core item with valid Matter/source/run references.
  attentionId = `capture-attention-${randomUUID()}`;
  const attention = await api('POST', '/attention', {
    projectId: project.id,
    request: {
      schema_version: 1, request_id: 'capture-attention-create', attention_id: attentionId, expected_revision: 0, action: 'create',
      payload: {
        descriptor: { title: 'Review Project Cedar source change', summary: 'A human should inspect the refreshed source before deciding.' },
        reason: 'The source-backed review needs human inspection after a source refresh.',
        next_action: { kind: 'inspect', label: 'Inspect refreshed sources', trigger: 'manual', due_at: null },
        source_refs: [{ kind: 'core', matter_id: matterProjection.matter.id, source_id: matterProjection.sources[0].id, version: matterProjection.sources[0].version, locator: 'fixture://project-cedar-source', role: 'supports', digest: matterProjection.sources[0].digest }],
        relation_refs: [{ kind: 'matter', id: matterProjection.matter.id, relation: 'about' }, { kind: 'session', id: matterSession.id, relation: 'origin' }, { kind: 'run', id: reviewRun.run.id, relation: 'execution' }],
      },
    },
  });
  result.attention = { id: attentionId, projectId: project.id, revision: attention.revision };
  result.scenarios.attention = { projectId: project.id, attentionId, registry: `/attention/registry?projectId=${project.id}` };

  // Global Attention conversation runs through its actual session and tools.
  const conversationId = randomUUID();
  const conversation = (await api('POST', '/attention/conversations', { conversationId })).session;
  const conversationRun = await runNatural(conversation, 'Help me inspect the review item for Project Cedar.', 'capture-attention-conversation');
  result.sessions.conversation = conversation.id;
  result.runs.conversation = conversationRun.run.id;
  result.scenarios.conversation = { sessionId: conversation.id, runId: conversationRun.run.id, attentionId };

  // A second project keeps Home visibly populated without inventing product
  // records. The plain chat is intentionally natural language.
  const otherSession = await makeSession(otherProject.id, 'Northside ledger reconciliation');
  const otherRun = await runNatural(otherSession, 'Review the ledger context.', 'capture-other-project');
  result.sessions.other = otherSession.id;
  result.runs.other = otherRun.run.id;
  result.scenarios.home = { projectIds: [project.id, otherProject.id], sessionIds: [matterSession.id, artifactSession.id, otherSession.id] };
  result.scenarios.models = { endpoint: '/provider-models', provider: (await api('GET', '/provider-models')).models };
  result.scenarios.integrations = { endpoint: '/extensions', extensions: (await api('GET', '/extensions')).extensions };
  result.scenarios.settings = { providerConfig: await api('GET', '/provider-config'), providerConnections: await api('GET', '/provider-connections') };

  // Active states are mutually exclusive because the service freezes all
  // work surfaces while any Run is active.
  if (active === 'approval') {
    const approvalSession = await makeSession(project.id, 'Exhibit index rebuild — approval', 'ask');
    const approvalRun = (await api('POST', `/sessions/${approvalSession.id}/runs`, { commandId: 'capture-approval', input: 'Write the exhibit index after checking the review materials.' })).run;
    const permission = await waitEvent(approvalSession.id, approvalRun.id, 'permission.open');
    result.sessions.approval = approvalSession.id;
    result.runs.approval = approvalRun.id;
    result.scenarios.approval = { sessionId: approvalSession.id, runId: approvalRun.id, permissionEvent: permission.data, state: 'waiting_user; leave unanswered for screenshot' };
  } else if (active === 'running') {
    runningMode = true;
    const runningSession = await makeSession(project.id, 'Source inspection — running', 'draft');
    const runningRun = (await api('POST', `/sessions/${runningSession.id}/runs`, { commandId: 'capture-running', input: 'Inspect the current workspace and summarize the source-backed review.' })).run;
    // Wait until the actual ws_read event and the slow final response are in
    // flight, then return while the Run remains active for the browser.
    await waitEvent(runningSession.id, runningRun.id, 'tool.start');
    result.sessions.running = runningSession.id;
    result.runs.running = runningRun.id;
    result.scenarios.running = { sessionId: runningSession.id, runId: runningRun.id, state: 'active slow stream; capture before completion' };
  } else {
    result.scenarios.approval = { recipe: 'run a natural ws_write prompt in a permissionMode=ask session and wait for permission.open' };
    result.scenarios.running = { recipe: 'rerun with --active running; capture while the slow response is active' };
  }

  await writeFile(manifestPath, JSON.stringify(result, null, 2) + '\n');
  console.log(JSON.stringify({ manifest: manifestPath, source_sha: sourceSha, origin: runtime.url, data_dir: dataDir, ids: { ...result.projects, ...result.sessions, ...result.runs, matter: result.matter?.id, candidate: result.matter?.candidate, attention: result.attention?.id } }));
  if (process.argv.includes('--seed-only')) {
    await runtime.close();
    if (!retain) await rm(dataDir, { recursive: true, force: true });
    process.exit(0);
  }
  // Keep the disposable server alive for a real browser capture. The caller
  // owns its lifecycle and can stop it with Ctrl-C; the manifest remains in a
  // random /tmp path and does not alter the pending site batch.
  await new Promise(resolve => {
    const stop = async () => { await runtime.close().catch(() => {}); if (!retain) await rm(dataDir, { recursive: true, force: true }); resolve(); };
    process.once('SIGINT', stop); process.once('SIGTERM', stop);
  });
} catch (error) {
  await runtime.close().catch(() => {});
  if (!retain) await rm(dataDir, { recursive: true, force: true });
  throw error;
}
