// Independent A1 boundary review: direct AsyncTasks + production RuntimeStore.
import assert from 'node:assert/strict'; import test from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import path from 'node:path'; import { setTimeout as delay } from 'node:timers/promises';
import { RuntimeStore } from '../server/store.mjs'; import { AsyncTasks } from '../server/async-tasks.mjs'; import { digestText } from '../server/async-task-state.mjs';
async function setup(adapter, canUse = () => true) { const dir=await mkdtemp(path.join(tmpdir(),'cw-boundary-')), store=await new RuntimeStore({dataDir:dir}).open(), project=await store.createProject('p'), session=await store.createSession({projectId:project.id,title:'s'}), made=await store.createRun({sessionId:session.id,input:'i',adapterId:'a',provider:{},commandId:'c',credentialGeneration:0}), tasks=new AsyncTasks({store,adapters:[adapter],canUse}); return {dir,store,project,session,run:made.run,tasks,close:async()=>{await tasks.close();await store.close();await rm(dir,{recursive:true,force:true});}}; }
function reader(hooks={}) { const text='independent immutable bytes',source={id:'source',version:'v1',digest:digestText(text)},calls={launch:0,query:0,cancel:0}, response=(taskId,status='running')=>({taskId,source,status,...(status==='succeeded'?{result:{text}}:{})}); return {source,text,calls,adapter:{id:'reader',version:'impl1',sources:[source],async launch({taskId}){calls.launch++;return hooks.launch?.(taskId,response)??response(taskId)},async query({taskId}){calls.query++;return hooks.query?.(taskId,response)??response(taskId)},async cancel({taskId}){calls.cancel++;return hooks.cancel?.(taskId,response)??response(taskId,'cancelled')}}}; }
async function launch(f,call='launch'){const t=await f.tasks.launch(f.run.id,call,{adapterId:'reader',sourceId:'source'});for(let i=0;i<30&&f.store.state.asyncTasks[0]?.execution.status==='queued';i++)await delay(2);return t;}
test('catalog staleness keeps durable result readable and refuses further adapter work',async()=>{const a=reader({launch:(id,r)=>r(id,'succeeded')}),f=await setup(a.adapter);try{const t=await launch(f);await delay(8);assert.equal(f.tasks.inspect(t.id,{projectId:f.project.id}).result.text,a.text);f.tasks.adapters.set('reader',{...a.adapter,sources:[]});assert.equal(f.tasks.inspect(t.id,{projectId:f.project.id}).availability,'historical');await assert.rejects(f.tasks.reconcile(t.id,{projectId:f.project.id}),{code:'task_source_stale'});assert.equal(f.tasks.inspect(t.id,{projectId:f.project.id}).result.digest,a.source.digest)}finally{await f.close()}});
test('policy rejection records dependency before adapter I/O, leaving Run unresolved',async()=>{let get=true;const a=reader(),f=await setup(a.adapter,n=>n==='async_launch'||get);try{const t=await launch(f);get=false;await assert.rejects(f.tasks.consume(f.run.id,'denied','get',{taskId:t.id}),{code:'task_policy_denied'});assert.equal(a.calls.query,0);assert.equal(f.store.state.asyncTasks[0].deliveries.length,1);assert.deepEqual(f.tasks.unresolved(f.run.id),[t.id])}finally{await f.close()}});
test('late query cannot overwrite cancellation and lost cancel ACK remains unresolved',async()=>{let release;const gate=new Promise(r=>release=r),a=reader({query:async(id,r)=>{await gate;return r(id,'succeeded')}}),f=await setup(a.adapter);try{const t=await launch(f),q=f.tasks.reconcile(t.id,{projectId:f.project.id});await delay(4);assert.equal((await f.tasks.cancel(t.id,{projectId:f.project.id})).execution.status,'cancelled');release();await assert.rejects(q,{code:'task_settlement_conflict'});assert.equal(f.tasks.inspect(t.id,{projectId:f.project.id}).execution.status,'cancelled')}finally{await f.close()}const b=reader({cancel:()=>{throw Error('lost ACK')}}),g=await setup(b.adapter);try{const t=await launch(g);assert.equal((await g.tasks.cancel(t.id,{projectId:g.project.id})).execution.status,'unknown');assert.deepEqual(g.tasks.unresolved(g.run.id),[t.id])}finally{await g.close()}});
test('stopped Run forbids dispatch and wait stays inside local budget',async()=>{const a=reader(),f=await setup(a.adapter);try{await f.store.updateRun(f.run.id,{status:'cancelled',admissionOpen:false});await assert.rejects(f.tasks.launch(f.run.id,'after-stop',{adapterId:'reader',sourceId:'source'}),{code:'task_admission_closed'});assert.equal(a.calls.launch,0)}finally{await f.close()}const b=reader(),g=await setup(b.adapter);try{const t=await launch(g),start=Date.now(),seen=await g.tasks.consume(g.run.id,'wait','wait',{taskId:t.id,waitMs:25});assert(Date.now()-start<350);assert.equal(seen.execution.status,'running');assert(b.calls.query>0)}finally{await g.close()}});
