import {boot} from '../../../../app/tests/helpers.mjs';
import {createHash} from 'node:crypto';
const hash=text=>createHash('sha256').update(text).digest('hex');
const h=await boot();
await h.api('POST','/extensions/evidence-memo/lifecycle',{action:'load'});
const session=await h.createSession({title:'Chat UI · synthetic review',permissionMode:'draft'});
await h.api('POST',`/sessions/${session.id}/extension`,{extensionId:'evidence-memo',input:{title:'Synthetic version review',sourceText:'Version one: delivery requires a recorded review.',profile:'file-memo-v1'}});
const projection=(await h.api('GET',`/sessions/${session.id}/surface`)).json.projection;
const source=projection.sources[0], text='# Recorded memo\n\nA complete synthetic file with `inline_code`, 中文和 emoji 😀.\n\nReview remains pending.\n';
const calls=[{name:'ws_write',arguments:{path:'out/memo.md',text}},{name:'ws_read',arguments:{path:'out/memo.md'}},{name:'se_submit_candidate',arguments:{artifact_text:'Synthetic candidate with a fixed file.',evidence:[{source_id:source.id,source_version:source.version,start:0,end:[...source.text].length,quote:source.text,digest:source.digest}],obligations:[],recordedFiles:[{path:'out/memo.md',sha256:hash(text)}]}}];
const created=(await h.api('POST',`/sessions/${session.id}/runs`,{commandId:'synthetic-complete',input:h.scriptInput(calls)})).json.run;
await h.pollRun(created.id);
const changedText='Version two: delivery requires a recorded review and a source check.';
const replaced=await h.api('POST',`/sessions/${session.id}/actions`,{extensionId:'evidence-memo',generation:0,fileCapabilityVersion:1,action:'replace_sources',payload:{revision:2,sources:[{...source,version:2,text:changedText,digest:hash(changedText)}]}});
if(replaced.status!==200) throw new Error(JSON.stringify(replaced.json));
await h.runtime.store.appendEvent({runId:created.id,type:'assistant.message',data:{text:'The memo is ready to inspect. The recorded write and read remain separate evidence; review is still pending.\n\n'+Array.from({length:14},(_,i)=>`Paragraph ${i+1}. Read this text while activity updates. The path \`out/a-long-directory-name/another-segment/memo.md\` and identifier \`recorded_version_sha256\` stay copyable.`).join('\n\n')}});
const err=(await h.api('POST',`/sessions/${session.id}/runs`,{commandId:'synthetic-error',input:h.scriptInput([{name:'ws_read',arguments:{path:'missing.txt'}}])})).json.run;await h.pollRun(err.id);
const pending=await h.createSession({title:'Chat UI · synthetic pending permission',permissionMode:'ask'});
await h.api('POST',`/sessions/${pending.id}/runs`,{commandId:'synthetic-pending',input:h.scriptInput([{name:'ws_write',arguments:{path:'draft.md',text:'Awaiting human permission.'}}])});
const plain=await h.createSession({title:'Chat UI · no sources',permissionMode:'draft'});
console.log(JSON.stringify({url:h.runtime.url,sessionId:session.id,pendingId:pending.id,plainId:plain.id,dataDir:h.dataDir}));
